import type { LucideIcon } from 'lucide-react';
import {
    User,
    FolderOpen,
    Cpu,
    FileText,
    Mail,
    TerminalSquare,
    Trash2,
    Headphones,
    PenTool,
    HardDrive,
    Calculator as CalcIcon,
    StickyNote,
    Bomb,
    Image as ImageIcon,
    Monitor,
} from 'lucide-react';

export interface AppConfig {
    id: string;
    title: string;
    /** Fallback glyph, used when `iconAsset` is absent or fails to load. */
    icon: LucideIcon;
    width?: number;
    height?: number;
    canMaximize?: boolean;
    canResize?: boolean;
    iconAsset?: string;
}

export const APPS: Record<string, AppConfig> = {
    about: {
        id: 'about',
        title: 'About Me',
        icon: User,
        iconAsset: '/icons/User Personalization.ico',
        width: 720,
        height: 540,
        canMaximize: true,
        canResize: true,
    },
    projects: {
        id: 'projects',
        title: 'My Projects',
        icon: FolderOpen,
        iconAsset: '/icons/Folder Open.ico',
        width: 820,
        height: 600,
        canMaximize: true,
        canResize: true,
    },
    skills: {
        id: 'skills',
        title: 'Skills & Tech',
        icon: Cpu,
        iconAsset: '/icons/Skills.ico',
        width: 760,
        height: 560,
        canMaximize: true,
        canResize: true,
    },
    resume: {
        id: 'resume',
        title: 'Resume.pdf',
        icon: FileText,
        iconAsset: '/icons/List File.ico',
        width: 560,
        height: 700,
        canMaximize: true,
        canResize: true,
    },
    contact: {
        id: 'contact',
        title: 'Contact Me',
        icon: Mail,
        iconAsset: '/icons/Phone.ico',
        width: 520,
        height: 440,
        canMaximize: false,
        canResize: true,
    },
    terminal: {
        id: 'terminal',
        title: 'Command Prompt',
        icon: TerminalSquare,
        iconAsset: '/icons/278.ico',
        width: 640,
        height: 420,
        canMaximize: true,
        canResize: true,
    },
    trash: {
        id: 'trash',
        title: 'Recycle Bin',
        icon: Trash2,
        iconAsset: '/icons/trash.png',
        width: 640,
        height: 460,
        canMaximize: true,
        canResize: true,
    },
    music: {
        id: 'music',
        title: 'Windows Media Player',
        icon: Headphones,
        iconAsset: '/icons/media-player.png',
        width: 380,
        height: 480,
        canMaximize: false,
        canResize: false,
    },
    paint: {
        id: 'paint',
        title: 'Paint',
        icon: PenTool,
        iconAsset: '/icons/paint.png',
        width: 840,
        height: 600,
        canMaximize: true,
        canResize: true,
    },
    mycomputer: {
        id: 'mycomputer',
        title: 'My Computer',
        icon: HardDrive,
        iconAsset: '/icons/My Computer.ico',
        width: 720,
        height: 500,
        canMaximize: true,
        canResize: true,
    },
    notepad: {
        id: 'notepad',
        title: 'Untitled - Notepad',
        icon: StickyNote,
        iconAsset: '/icons/List File.ico',
        width: 600,
        height: 460,
        canMaximize: true,
        canResize: true,
    },
    calculator: {
        id: 'calculator',
        title: 'Calculator',
        icon: CalcIcon,
        iconAsset: '/icons/Display.ico',
        width: 240,
        height: 320,
        canMaximize: false,
        canResize: false,
    },
    minesweeper: {
        id: 'minesweeper',
        title: 'Minesweeper',
        icon: Bomb,
        iconAsset: '/icons/Minesweeper.ico',
        width: 340,
        height: 420,
        canMaximize: false,
        canResize: false,
    },
    settings: {
        id: 'settings',
        title: 'Display Properties',
        icon: Monitor,
        iconAsset: '/icons/control-panel.png',
        width: 520,
        height: 540,
        canMaximize: false,
        canResize: false,
    },
    imageviewer: {
        id: 'imageviewer',
        title: 'Windows Picture and Fax Viewer',
        icon: ImageIcon,
        iconAsset: '/icons/Display.ico',
        width: 640,
        height: 520,
        canMaximize: true,
        canResize: true,
    },
};

export const DESKTOP_ICONS = [
    'mycomputer',
    'about',
    'projects',
    'skills',
    'resume',
    'contact',
    'music',
    'paint',
    'notepad',
    'calculator',
    'minesweeper',
    'terminal',
    'trash',
];
